variables:
  IMAGE_NAME: korngsamnang/python-demo
  IMAGE_TAG: python-app-1.0

run_tests:
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install -y make
  script:
    - make test

build_image:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: '/certs'
  before_script:
    - echo "Branch: ${CI_COMMIT_BRANCH}" # Confirm branch
    - echo "DOCKER_USER: ${DOCKER_USER}" # Check variable
    - echo "DOCKER_PASS is set: ${DOCKER_PASS:+yes}" # Check if password exists
    - echo "$DOCKER_PASS" | docker --debug login -u "$DOCKER_USER" --password-stdin # Debug login
  script:
    - docker build ./build -t $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:$IMAGE_TAG
