variables:
  IMAGE_NAME: korngsamnang/python-demo
  IMAGE_TAG: python-app-1.0

run_tests:
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install -y make # Ensure non-interactive installation
  script:
    - make test

build_image:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: '/certs'
  before_script:
    - echo "Branch: ${CI_COMMIT_BRANCH}" # Log the current branch
    - echo "DOCKER_USER: ${DOCKER_USER}" # Verify the username is set
    - echo "DOCKER_PASS is set: ${DOCKER_PASS:+yes}" # Check if password exists (prints 'yes' if non-empty)
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin # Login to Docker
  script:
    - docker build ./build -t $IMAGE_NAME:$IMAGE_TAG # Build Docker image
    - docker push $IMAGE_NAME:$IMAGE_TAG # Push Docker image to the registry
